
package com.atividadeavaliativa.employeemanagement.view;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JMenuItem;


public class TelaPrincipalView extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipalView
     */
    public TelaPrincipalView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbVersao = new javax.swing.JLabel();
        btTelaPrincipal = new javax.swing.JButton();
        lbFuncionarios = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuItemManterFuncionario = new javax.swing.JMenuItem();
        menuItemBuscarFuncionario = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuItemCalculaSalario = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuItemFerramenta = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Principal");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lbVersao.setForeground(new java.awt.Color(51, 51, 51));
        lbVersao.setText("1.2");

        btTelaPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        btTelaPrincipal.setText("JSON");
        btTelaPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTelaPrincipalActionPerformed(evt);
            }
        });

        lbFuncionarios.setBackground(new java.awt.Color(51, 51, 51));
        lbFuncionarios.setForeground(new java.awt.Color(51, 51, 51));
        lbFuncionarios.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lbVersao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(btTelaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(lbFuncionarios)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btTelaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbVersao)
                    .addComponent(lbFuncionarios))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));

        jMenu1.setBackground(new java.awt.Color(255, 255, 255));
        jMenu1.setForeground(new java.awt.Color(51, 51, 51));
        jMenu1.setText("Funcionario");

        menuItemManterFuncionario.setText("Manter Funcionário");
        jMenu1.add(menuItemManterFuncionario);

        menuItemBuscarFuncionario.setText("Buscar Funcionário");
        menuItemBuscarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemBuscarFuncionarioActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemBuscarFuncionario);

        jMenuBar1.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(255, 255, 255));
        jMenu2.setForeground(new java.awt.Color(51, 51, 51));
        jMenu2.setText("Salário");

        menuItemCalculaSalario.setText("Calcular Salário");
        jMenu2.add(menuItemCalculaSalario);

        jMenuBar1.add(jMenu2);

        jMenu4.setBackground(new java.awt.Color(255, 255, 255));
        jMenu4.setForeground(new java.awt.Color(51, 51, 51));
        jMenu4.setText("Ferramentas");

        menuItemFerramenta.setText("Configuração Log");
        menuItemFerramenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemFerramentaActionPerformed(evt);
            }
        });
        jMenu4.add(menuItemFerramenta);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(305, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemBuscarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemBuscarFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemBuscarFuncionarioActionPerformed

    private void menuItemFerramentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemFerramentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemFerramentaActionPerformed

    private void btTelaPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTelaPrincipalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btTelaPrincipalActionPerformed

    public JButton getBtTelaPrincipal() {
        return btTelaPrincipal;
    }

    public JLabel getLbFuncionarios() {
        return lbFuncionarios;
    }

    public void setLbFuncionarios(String quantidadeFuncionarios) {
        this.lbFuncionarios.setText(quantidadeFuncionarios); 
    }

    public void setLbVersao(JLabel lbVersao) {
        this.lbVersao = lbVersao;
    }
    
    public JLabel getLbVersao() {
        return lbVersao;
    }

    public JMenuItem getMenuItemBuscarFuncionario() {
        return menuItemBuscarFuncionario;
    }

    public JMenuItem getMenuItemCalculaSalario() {
        return menuItemCalculaSalario;
    }

    public JMenuItem getMenuItemManterFuncionario() {
        return menuItemManterFuncionario;
    }

    public JMenuItem getMenuItemFerramenta() {
        return menuItemFerramenta;
    }
    

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btTelaPrincipal;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbFuncionarios;
    private javax.swing.JLabel lbVersao;
    private javax.swing.JMenuItem menuItemBuscarFuncionario;
    private javax.swing.JMenuItem menuItemCalculaSalario;
    private javax.swing.JMenuItem menuItemFerramenta;
    private javax.swing.JMenuItem menuItemManterFuncionario;
    // End of variables declaration//GEN-END:variables


}
